"""
Django settings for civilApp project.

Generated by 'django-admin startproject' using Django 5.2.6.

Más info:
https://docs.djangoproject.com/en/5.2/topics/settings/
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# === Paths ===
BASE_DIR = Path(__file__).resolve().parent.parent


# === Seguridad (IMPORTANTE en producción) ===
SECRET_KEY = 'django-insecure-eq$c3^lr17r6btsvw^fh2@@cg73a)m#u*h!@&5@$i*mz@3buz)'
DEBUG = True
ALLOWED_HOSTS = []  # en prod, agrega tu dominio o IP


# === Aplicaciones instaladas ===
INSTALLED_APPS = [
    # Django apps por defecto
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Tus apps
    'pages',
    'accounts',
    'gestdocu',
]


# === Middleware ===
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]


# === Configuración de URLs y WSGI ===
ROOT_URLCONF = 'civilApp.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        # Directorio global de templates
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',   # útil en dev
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'civilApp.wsgi.application'


# === Base de datos (PostgreSQL) ===
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'gestdocum',
        'USER': 'postgres',
        'PASSWORD': 'Ics2606',
        'HOST': 'localhost',
        'PORT': '5432',
    }
}


# === Validación de contraseñas ===
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# === Usuario personalizado ===
AUTH_USER_MODEL = 'accounts.User'


# === Internacionalización ===
LANGUAGE_CODE = 'es'          # 👈 mejor en español
TIME_ZONE = 'America/La_Paz'
USE_I18N = True
USE_TZ = True


# === Archivos estáticos (CSS, JS, imágenes globales) ===
STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'static']  # carpeta global de estáticos
STATIC_ROOT = BASE_DIR / 'staticfiles'    # para producción (collectstatic)


# === Archivos subidos por usuarios (MEDIA) ===
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'


# === Configuración por defecto de clave primaria ===
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
