# Generated by Django 5.2.6 on 2025-10-08 04:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casos', '0003_expediente_alter_caso_estado_alter_caso_prioridad'),
    ]

    operations = [
        migrations.AddField(
            model_name='expediente',
            name='caso',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='expedientes', to='casos.caso'),
            preserve_default=False,
        ),
    ]
